newsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from website.views import *
app_name='website'
urlpatterns = [
    
    path('',index_view,name='index'),
    path('about',about_view,name='about'),
    path('contact',contact_view,name='contact'),
    path('work',work_view,name='work'),
    path('blog',blog_view,name='blog')

]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

from django.http import HttpResponse

def index_view(request):
    return render(request,'website/index.html')

def about_view(request):
    return render(request,'website/about.html')


def contact_view(request):
    return render(request,'website/contact.html')

def work_view(request):
    return render(request,'website/work.html')

def blog_view(request):
    return render(request,'website/blog.html')



# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Willism</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,700|Roboto:400,700&display=swap" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css'%}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css'%}" rel="stylesheet" />
</head>

<body>
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-11 offset-md-1 px-0">
            <nav class="navbar navbar-expand-lg custom_nav-container pt-3">
              <a class="navbar-brand" href="index.html">
                <span>
                  Willism
                </span>
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex ml-auto flex-column flex-lg-row align-items-center">
                  <ul class="navbar-nav  ">
                    <li class="nav-item ">
                      <a class="nav-link pl-0" href="{% url 'website:index'%}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item ">
                      <a class="nav-link" href="{% url 'website:about'%}"> About </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:work'%}">MyWork </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:blog'%}"> Blog </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:contact'%}">Contact us</a>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <!-- end header section -->
  </div>
  <!-- end hero area -->

  <!-- about section -->
  {% block content %}

  {% endblock %}

 <!-- footer section -->
 <section class="container-fluid footer_section">
    <div class="container">
      <p>
        &copy; 2020 All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </section>
  <!-- footer section -->

  <script src="{% static 'js/jquery-3.4.1.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.js'%}"></script>

  <script>
    function openNav() {
      document.getElementById("myNav").style.width = "100%";
    }

    function closeNav() {
      document.getElementById("myNav").style.width = "0%";
    }
  </script>

</body>

</html>

templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <section class="about_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          About
        </h2>
      </div>
      <div class="box layout_padding2-top layout_padding-bottom">
        <div class="detail-box">
          <p>
            It is a long established fact that a reader will be distracted by
            the readable content of a page when looking at its layout. The
            point of using LoremIt is a long established fact that a reader
            will be distracted by the readable content of a page when looking
            at its layout. The point of using Lorem
          </p>
        </div>
        <div class="img-box">
          <img src="{% static 'images/about-img.jpg' %}" alt="" />
        </div>
      </div>
    </div>
    <div class="btn-box">
      <a href="">
        Read More
      </a>
    </div>
  </section>

  <!-- end about section -->

  <!-- info section -->
  <section class="info_section layout_padding-top layout_padding2-bottom">
    <div class="container">
      <div class="social_container">
        <h2>
          Follow Us
        </h2>
        <div class="social_box">
          <a href="">
            <img src="{% static 'images/fb.png' %}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/twitter.png' %}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/linkedin.png' %}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/youtube.png' %}" alt="" />
          </a>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->

{% endblock %}

templates/website/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content%}

  </div>
  <!-- end hero area -->

  <!-- blog section -->
  <section class="blog_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          See Our Blog
        </h2>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="box">
            <div class="img-box">
              <img src="{% static 'images/b-1.jpg' %}" alt="" />
            </div>
            <div class="detail-box">
              <h4>
                Readable content of a page
              </h4>
              <p>
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout.
                The point of using Lorem
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="box">
            <div class="img-box">
              <img src="{% static 'images/b-2.jpg' %}" alt="" />
            </div>
            <div class="detail-box">
              <h4>
                Readable content of a page
              </h4>
              <p>
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout.
                The point of using Lorem
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="box">
            <div class="img-box">
              <img src="{% static 'images/b-3.jpg' %}" alt="" />
            </div>
            <div class="detail-box">
              <h4>
                Readable content of a page
              </h4>
              <p>
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout.
                The point of using Lorem
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end blog section -->

  <!-- info section -->
  <section class="info_section layout_padding-top layout_padding2-bottom">
    <div class="container">
      <div class="social_container">
        <h2>
          Follow Us
        </h2>
        <div class="social_box">
          <a href="">
            <img src="{% static 'images/fb.png' %}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/twitter.png' %}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/linkedin.png' %}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/youtube.png' %}" alt="" />
          </a>
        </div>
      </div>
    </div>
  </section>

{% endblock %} 

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  </div>
  <!-- end hero area -->

  <!-- contact section -->

  <section class="contact_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Contact Us
        </h2>
      </div>
      <div class="">
        <div class="">
          <div class="row">
            <div class="col-md-9 mx-auto">
              <div class="contact-form">
                <form action="">
                  <div>
                    <input type="text" placeholder="Full Name " />
                  </div>
                  <div>
                    <input type="text" placeholder="Phone Number" />
                  </div>
                  <div>
                    <input type="email" placeholder="Email Address" />
                  </div>
                  <div>
                    <input type="text" placeholder="Message" class="input_message" />
                  </div>
                  <div class="d-flex justify-content-center">
                    <button type="submit" class="btn_on-hover">
                      Send
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end contact section -->

  <!-- info section -->
  <section class="info_section layout_padding-top layout_padding2-bottom">
    <div class="container">
      <div class="social_container">
        <h2>
          Follow Us
        </h2>
        <div class="social_box">
          <a href="">
            <img src="{% static 'images/fb.png' %}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/twitter.png' %}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/linkedin.png' %}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/youtube.png' %}" alt="" />
          </a>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->

{% endblock %}

templates/website/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <!-- slider section -->
      <div class="slider_section">
        <div
          id="carouselExampleControls"
          class="carousel slide"
          data-ride="carousel"
        >
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-lg-6 offset-lg-1">
                    <div class="detail-box">
                      <div class="heading_box">
                        <h2>i Am Willism My <span>Creative</span></h2>
                        <h1>
                          Portfolio
                        </h1>
                      </div>
                      <div>
                        <a href="">
                          Read More
                        </a>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-5 px-0">
                    <div class="img-box">
                      <img src="{% static 'images/slider-img.png' %}" alt="" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="carousel-item">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-lg-6 offset-lg-1">
                    <div class="detail-box">
                      <div class="heading_box">
                        <h2>i Am Willism My <span>Creative</span></h2>
                        <h1>
                          Portfolio
                        </h1>
                      </div>
                      <div>
                        <a href="">
                          Read More
                        </a>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-5 px-0">
                    <div class="img-box">
                      <img src="{% static 'images/slider-img.png' %}" alt="" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="carousel-item">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-lg-6 offset-lg-1">
                    <div class="detail-box">
                      <div class="heading_box">
                        <h2>i Am Willism My <span>Creative</span></h2>
                        <h1>
                          Portfolio
                        </h1>
                      </div>
                      <div>
                        <a href="">
                          Read More
                        </a>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-5 px-0">
                    <div class="img-box">
                      <img src="{% static 'images/slider-img.png' %}" alt="" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="slider_btn-container">
          <a
            class="carousel-control-prev"
            href="#carouselExampleControls"
            role="button"
            data-slide="prev"
          >
            <span class="sr-only">Previous</span>
          </a>
          <a
            class="carousel-control-next"
            href="#carouselExampleControls"
            role="button"
            data-slide="next"
          >
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

      <!-- end slider section -->
    </div>
    <!-- end hero area -->

    <!-- design section -->

    <section class="design_section layout_padding-top">
      <div class="container">
        <div class="heading_container">
          <h2>
            UI/UX Design
          </h2>
        </div>
        <div class="design_container layout_padding2">
          <div class="box b-1">
            <h5>
              User <br />
              Experience
            </h5>
          </div>
          <div class="box b-2">
            <h5>
              Interface <br />
              Design
            </h5>
          </div>
          <div class="box b-3">
            <h5>
              Mobile Apps
            </h5>
          </div>
        </div>
      </div>
    </section>

    <!-- end design section   -->
    <div>
      <hr class="section_hr" />
    </div>
    <!-- about section -->

    <section class="about_section layout_padding-bottom">
      <div class="container">
        <div class="heading_container">
          <h2>
            About
          </h2>
        </div>
        <div class="box layout_padding2-top layout_padding-bottom">
          <div class="detail-box">
            <p>
              It is a long established fact that a reader will be distracted by
              the readable content of a page when looking at its layout. The
              point of using LoremIt is a long established fact that a reader
              will be distracted by the readable content of a page when looking
              at its layout. The point of using Lorem
            </p>
          </div>
          <div class="img-box">
            <img src="{% static 'images/about-img.jpg' %}" alt="" />
          </div>
        </div>
      </div>
      <div class="btn-box">
        <a href="">
          Read More
        </a>
      </div>
    </section>

    <!-- end about section -->

    <!-- project section -->

    <section class="project_section layout_padding-bottom">
      <div class="container">
        <div class="heading_container">
          <h2>
            Our Projects
          </h2>
        </div>
        <div class="project_container layout_padding2-top">
          <div class="box">
            <img src="{% static 'images/p-1.jpg' %}" alt="" />
          </div>
          <div class="box">
            <img src="{% static 'images/p-2.jpg' %}" alt="" />
          </div>
          <div class="box">
            <img src="{% static 'images/p-3.jpg' %}" alt="" />
          </div>
          <div class="box">
            <img src="{% static 'images/p-4.jpg' %}" alt="" />
          </div>
          <div class="box">
            <img src="{% static 'images/p-5.jpg' %}" alt="" />
          </div>
          <div class="box">
            <img src="{% static 'images/p-6.jpg' %}" alt="" />
          </div>
          <div class="box">
            <img src="{% static 'images/p-7.jpg' %}" alt="" />
          </div>
          <div class="box">
            <img src="{% static 'images/p-8.jpg' %}" alt="" />
          </div>
          <div class="box">
            <img src="{% static 'images/p-9.jpg' %}" alt="" />
          </div>
        </div>
      </div>
    </section>

    <!-- end project section -->

    <!-- expand section -->

    <section class="expand_section">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6">
            <div class="img-box">
              <img src="{% static 'images/expand-img.jpg' %}" alt="" />
            </div>
          </div>
          <div class="col-md-6">
            <div class="detail-box">
              <h2>
                Expand your horizons, explore ours. It's all here. It's only
                here.
              </h2>
              <p>
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout.
                The point of using LoremIt is a long established fact that a
                reader will be distracted by the readable content of a page when
                looking at its layout. The point of using Lorem
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- end expand section -->
    <div>
      <hr class="section_hr" />
    </div>
    <!-- blog section -->
    <section class="blog_section layout_padding-bottom">
      <div class="container">
        <div class="heading_container">
          <h2>
            See Our Blog
          </h2>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="box">
              <div class="img-box">
                <img src="{% static 'images/b-1.jpg' %}" alt="" />
              </div>
              <div class="detail-box">
                <h4>
                  Readable content of a page
                </h4>
                <p>
                  It is a long established fact that a reader will be distracted
                  by the readable content of a page when looking at its layout.
                  The point of using Lorem
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="box">
              <div class="img-box">
                <img src="{% static 'images/b-2.jpg' %}" alt="" />
              </div>
              <div class="detail-box">
                <h4>
                  Readable content of a page
                </h4>
                <p>
                  It is a long established fact that a reader will be distracted
                  by the readable content of a page when looking at its layout.
                  The point of using Lorem
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="box">
              <div class="img-box">
                <img src="{% static 'images/b-3.jpg' %}" alt="" />
              </div>
              <div class="detail-box">
                <h4>
                  Readable content of a page
                </h4>
                <p>
                  It is a long established fact that a reader will be distracted
                  by the readable content of a page when looking at its layout.
                  The point of using Lorem
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- end blog section -->

    <!-- contact section -->

    <section class="contact_section layout_padding">
      <div class="container">
        <div class="heading_container">
          <h2>
            Contact Us
          </h2>
        </div>
        <div class="">
          <div class="">
            <div class="row">
              <div class="col-md-9 mx-auto">
                <div class="contact-form">
                  <form action="">
                    <div>
                      <input type="text" placeholder="Full Name " />
                    </div>
                    <div>
                      <input type="text" placeholder="Phone Number" />
                    </div>
                    <div>
                      <input type="email" placeholder="Email Address" />
                    </div>
                    <div>
                      <input
                        type="text"
                        placeholder="Message"
                        class="input_message"
                      />
                    </div>
                    <div class="d-flex justify-content-center">
                      <button type="submit" class="btn_on-hover">
                        Send
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- end contact section -->

    <!-- info section -->
    <section class="info_section layout_padding-top layout_padding2-bottom">
      <div class="container">
        <div class="social_container">
          <h2>
            Follow Us
          </h2>
          <div class="social_box">
            <a href="">
              <img src="{% static 'images/fb.png' %}" alt="" />
            </a>
            <a href="">
              <img src="{% static 'images/twitter.png' %}" alt="" />
            </a>
            <a href="">
              <img src="{% static 'images/linkedin.png' %}" alt="" />
            </a>
            <a href="">
              <img src="{% static 'images/youtube.png' %}" alt="" />
            </a>
          </div>
        </div>
      </div>
    </section>

    <!-- end info_section -->

{% endblock %}

templates/website/work.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  </div>
  <!-- end hero area -->

  <!-- project section -->

  <section class="project_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Our Projects
        </h2>
      </div>
      <div class="project_container layout_padding2-top">
        <div class="box">
          <img src="{% static 'images/p-1.jpg'%}" alt="" />
        </div>
        <div class="box">
          <img src="{% static 'images/p-2.jpg'%}" alt="" />
        </div>
        <div class="box">
          <img src="{% static 'images/p-3.jpg'%}" alt="" />
        </div>
        <div class="box">
          <img src="{% static 'images/p-4.jpg'%}" alt="" />
        </div>
        <div class="box">
          <img src="{% static 'images/p-5.jpg'%}" alt="" />
        </div>
        <div class="box">
          <img src="{% static 'images/p-6.jpg'%}" alt="" />
        </div>
        <div class="box">
          <img src="{% static 'images/p-7.jpg'%}" alt="" />
        </div>
        <div class="box">
          <img src="{% static 'images/p-8.jpg'%}" alt="" />
        </div>
        <div class="box">
          <img src="{% static 'images/p-9.jpg'%}" alt="" />
        </div>
      </div>
    </div>
  </section>

  <!-- end project section -->

  <!-- info section -->
  <section class="info_section layout_padding-top layout_padding2-bottom">
    <div class="container">
      <div class="social_container">
        <h2>
          Follow Us
        </h2>
        <div class="social_box">
          <a href="">
            <img src="{% static 'images/fb.png'%}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/twitter.png'%}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/linkedin.png'%}" alt="" />
          </a>
          <a href="">
            <img src="{% static 'images/youtube.png'%}" alt="" />
          </a>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->

{% endblock %}